---
sidebar: sidebar
permalink: asup-dcn-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: asup.dcn events
---

= asup.dcn events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== asup.dcn.sync.failed
*Severity*::
NOTICE
*Description*::
This message occurs when the AutoSupport configurations in the ONTAP cluster fail to propagate to the data compute nodes and the AI Data Engine cluster. The system will automatically retry the propagation in the background using exponentially increasing intervals until it is successful.
*Corrective Action*::
(None).
*Syslog Message*::
AutoSupport configurations failed to propagate to data compute nodes and AI Data Engine cluster. Error: %s
*Parameters*::
*FailureReason* (STRING): Sync failure reason.

== asup.dcn.sync.success
*Severity*::
NOTICE
*Description*::
This message occurs when the AutoSupport configurations in the ONTAP cluster have successfully propagated to the data compute nodes and the AI Data Engine cluster after a previous failure.
*Corrective Action*::
(None).
*Syslog Message*::
AutoSupport configurations successfully propagated to data compute nodes and AI Data Engine cluster.
*Parameters*::
(None).
