---
sidebar: sidebar
permalink: spm-bcomd-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: spm.bcomd events
---

= spm.bcomd events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
spm.bcomd events occur when the Blocks Configuration and Operations Manager Daemon (BCOMd) aborts.


== spm.bcomd.process.exit
*Severity*::
ALERT
*Description*::
This message occurs when the Blocks Configuration and Operations Manager Daemon (BCOMd) aborts. This can be due to one or more causes and might be related to some recent or previous operations.
*Corrective Action*::
The system attempts to recover by restarting the daemon. If the daemon does not recover within the threshold number of retries, an AutoSupport message is sent. If your system is not configured to send AutoSupport messages and the issue persists, contact NetApp technical support.
*Syslog Message*::
Blocks Configuration and Operations Manager Daemon (BCOMd) with ID %d aborted as a result of signal %s. The daemon will attempt to restart.
*Parameters*::
*id* (INT): Process identifier.
*cause* (STRING): Plain text description of why the process aborted.
