---
sidebar: sidebar
permalink: wafl-fa-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.fa events
---

= wafl.fa events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
wafl.fa events occur when a FlexAggregate is waiting for other FlexAggregates to reach the same iron state.


== wafl.fa.iron.sync.waiting
*Severity*::
NOTICE
*Description*::
This message occurs when a FlexAggregate is waiting for other FlexAggregates to reach the same iron state. Failure to reach the same iron state stalls wafliron running on the storage pod.
*Corrective Action*::
Run "wafliron status" on the storage pod to check state of other FlexAggregates.
*Syslog Message*::
FlexAggregate "%s" is waiting for other FlexAggregates to reach the iron state : %s.
*Parameters*::
*flexaggrname* (STRING): FlexAggregate name.
*iron_state* (STRING): Current iron state of the FlexAggregate.

== wafl.fa.mark.inconsistent
*Severity*::
ALERT
*Description*::
This message occurs when an aggregate is being marked inconsistent.
*Corrective Action*::
Contact NetApp technical support.
*Syslog Message*::
Flexaggr with ID: "%d" is marked inconsistent due to "%s". Call support for assistance.
*Parameters*::
*flexaggr_id* (INT): ID of the flexaggregate.
*reason* (STRING): Reason for EMS being triggered.
